name: Download and Update Czip Db File
on:
  workflow_dispatch:
  schedule:
    - cron: '10 2,5,9,12,15 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  contents: write
env:
  USER_AGENT: "Mozilla/5.0 (Macintosh; Intel Mac OS X 12) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        env:
          DOWNLOAD_TOKEN: ${{ secrets.DOWNLOAD_TOKEN }}
          CZDB_TOKEN: ${{ secrets.CZDB_TOKEN }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.QQWRY }}
        run: |
          pnpm i
          pnpm run build
