name: Download and Update Czip Db File
on:
  workflow_dispatch:
  schedule:
    - cron: '10 2,5,9,12,15 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  contents: write
env:
  USER_AGENT: "Mozilla/5.0 (Macintosh; Intel Mac OS X 12) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Checkout
        uses: actions/checkout@v3
      - name: Parse
        env:
          DOWNLOAD_TOKEN: ${{ secrets.DOWNLOAD_TOKEN }}
          CZDB_TOKEN: ${{ secrets.CZDB_TOKEN }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.QQWRY }}
        run: |
          pnpm i
          pnpm run build
      - name: Check if tag exists
        run: |
          dat_date=$(cat version)
          echo "dat_date=${dat_date}" >> $GITHUB_ENV
          git fetch --tags
          echo "Value of dat_date: ${dat_date}"
          if git rev-parse ${dat_date} >/dev/null 2>&1; then
            echo "Tag already exists, skipping create release"
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          fi
      - name: Calculate file hash value
        id: calculate_hash_value
        if: env.TAG_EXISTS != 'true'
        run: |
          echo "FILE_HASH=$(sha256sum ./dist/qqwry.dat | awk '{ print $1 }')" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        if: env.TAG_EXISTS != 'true'
        with:
          commit: ${{ env.GITHUB_SHA }}
          tag: ${{ env.dat_date }}
          token: ${{ secrets.QQWRY }}
          artifacts: ./dist/qqwry.dat
          body: |
            #### czip db file info
            
            | Name               | Value                      |
            | :----------------: | :------------------------: |
            | Dat File Fast Download: | https://raw.gitmirror.com/nmgliangwei/qqwry/main/qqwry.dat |
            | Dat File sha256: | qqwry.dat: ${{ env.FILE_HASH }} |
            <p align="right"><code>Version: ${{ env.dat_date }} </code></p>
#      - name: Calculate repository hash value
#        id: calculate_repo_hash_value
#        if: env.TAG_EXISTS != 'true'
#        run: |
#          echo "REPO_HASH=$(git show main:qqwry.dat | sha256sum | awk '{ print $1 }')" >> $GITHUB_ENV
#      - name: Check for changes in qqwry.dat
#        id: check
#        if: env.TAG_EXISTS != 'true'
#        run: |
#          if [ ! -f qqwry.dat ] ; then
#            echo "File does not exist"
#            echo "RUN_NEXT_STEP=true" >> $GITHUB_ENV
#          else
#            #比较上面的两个hash值是否相等
#            if [ "${{ env.FILE_HASH }}" != "${{ env.REPO_HASH }}" ]; then
#              echo "File has changed"
#              echo "RUN_NEXT_STEP=true" >> $GITHUB_ENV
#            else
#              echo "File has not changed"
#            fi
#          fi
      - name: Commit qqwry.dat
#        if: env.RUN_NEXT_STEP == 'true' && env.TAG_EXISTS != 'true'
        if: env.TAG_EXISTS != 'true'
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          git config --global user.name $GIT_USERNAME
          git config --global user.email $GIT_EMAIL
          if ! git status -s | grep qqwry.dat --quiet ; then
            mv ./dist/qqwry.dat qqwry.dat
            git add qqwry.dat version
            git commit -m "Update dat File in  ${{ env.dat_date }}"
            git push
          fi